<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>datacap</artifactId>
        <groupId>io.edurt.datacap</groupId>
        <version>2026.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <name>datacap-server</name>
    <artifactId>datacap-server</artifactId>
    <description>DataCap - Core - Server</description>

    <properties>
        <h2.version>2.1.214</h2.version>
        <findbugs.version>3.0.1</findbugs.version>
        <frontend-maven-plugin.version>1.15.0</frontend-maven-plugin.version>
        <node.version>v20.18.1</node.version>
        <pnpm.version>9.13.2</pnpm.version>
        <jaxb-api.version>2.3.1</jaxb-api.version>
        <jaxb-impl.version>2.3.1</jaxb-impl.version>
        <jaxb-core.version>2.3.0.1</jaxb-core.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
            <version>${springboot.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>log4j-slf4j-impl</artifactId>
                    <groupId>org.apache.logging.log4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>${redis.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>${jaxb-api.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>${jaxb-core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>${jaxb-impl.version}</version>
        </dependency>
        <dependency>
            <groupId>io.edurt.datacap</groupId>
            <artifactId>datacap-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.edurt.datacap</groupId>
            <artifactId>datacap-common</artifactId>
        </dependency>
        <dependency>
            <groupId>io.edurt.datacap</groupId>
            <artifactId>datacap-service</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.edurt.datacap</groupId>
            <artifactId>datacap-security</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.edurt.datacap</groupId>
            <artifactId>datacap-plugin</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.edurt.datacap</groupId>
            <artifactId>datacap-convert-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.edurt.datacap</groupId>
            <artifactId>datacap-notify-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.edurt.datacap</groupId>
            <artifactId>datacap-parser-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.edurt.datacap</groupId>
            <artifactId>datacap-executor-spi</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.edurt.datacap</groupId>
            <artifactId>datacap-scheduler-spi</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>${frontend-maven-plugin.version}</version>
                <configuration>
                    <installDirectory>../datacap-ui/</installDirectory>
                    <workingDirectory>../datacap-ui/</workingDirectory>
                    <nodeVersion>${node.version}</nodeVersion>
                    <pnpmVersion>${pnpm.version}</pnpmVersion>
                </configuration>
                <executions>
                    <execution>
                        <id>install node and pnpm</id>
                        <goals>
                            <goal>install-node-and-pnpm</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>pnpm install</id>
                        <goals>
                            <goal>pnpm</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pnpm run build</id>
                        <goals>
                            <goal>pnpm</goal>
                        </goals>
                        <configuration>
                            <arguments>run build</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>${assembly-plugin.version}</version>
                <configuration>
                    <descriptors>
                        <descriptor>../../configure/assembly/server.xml</descriptor>
                    </descriptors>
                    <skipAssembly>false</skipAssembly>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>../../dist</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}</directory>
                                    <includes>
                                        <include>${project.artifactId}*.tar.gz</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <directory>../datacap-ui/dist</directory>
                <targetPath>resources</targetPath>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.*</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>
