const data = {
  "headers": [
    "id",
    "state",
    "create_time",
    "end_time",
    "plugin_id",
    "content",
    "message",
    "elapsed",
    "user_id"
  ],
  "types": [
    "BIGINT",
    "VARCHAR",
    "MEDIUMTEXT",
    "MEDIUMTEXT",
    "BIGINT",
    "TEXT",
    "TEXT",
    "BIGINT",
    "BIGINT"
  ],
  "columns": [
    {
      "id": "136",
      "state": "SUCCESS",
      "create_time": "2022-10-17 15:19:58.622",
      "end_time": "2022-10-17 15:20:04.701",
      "plugin_id": "68",
      "content": "show databases",
      "message": "null",
      "elapsed": "6079",
      "user_id": "1"
    },
    {
      "id": "137",
      "state": "SUCCESS",
      "create_time": "2022-10-17 15:20:11.919",
      "end_time": "2022-10-17 15:20:14.801",
      "plugin_id": "68",
      "content": "show tables",
      "message": "null",
      "elapsed": "2882",
      "user_id": "1"
    },
    {
      "id": "138",
      "state": "SUCCESS",
      "create_time": "2022-10-17 15:20:31.691",
      "end_time": "2022-10-17 15:20:34.586",
      "plugin_id": "68",
      "content": "select * from github_events limit 100",
      "message": "null",
      "elapsed": "2895",
      "user_id": "1"
    },
    {
      "id": "139",
      "state": "SUCCESS",
      "create_time": "2022-10-17 23:45:09.79",
      "end_time": "2022-10-17 23:45:12.994",
      "plugin_id": "68",
      "content": "select * from github_events limit 100",
      "message": "null",
      "elapsed": "3204",
      "user_id": "1"
    },
    {
      "id": "179",
      "state": "FAILURE",
      "create_time": "2022-10-18 00:37:18.319",
      "end_time": "2022-10-18 00:37:19.182",
      "plugin_id": "63",
      "content": "use datacap;",
      "message": "Error -1 (00000) : while preparing SQL: use datacap;",
      "elapsed": "863",
      "user_id": "1"
    },
    {
      "id": "180",
      "state": "FAILURE",
      "create_time": "2022-10-18 00:37:25.906",
      "end_time": "2022-10-18 00:37:26.056",
      "plugin_id": "63",
      "content": "show database",
      "message": "Error -1 (00000) : while preparing SQL: show database",
      "elapsed": "150",
      "user_id": "1"
    },
    {
      "id": "181",
      "state": "FAILURE",
      "create_time": "2022-10-18 00:37:27.856",
      "end_time": "2022-10-18 00:37:28.004",
      "plugin_id": "63",
      "content": "show databases",
      "message": "Error -1 (00000) : while preparing SQL: show databases",
      "elapsed": "148",
      "user_id": "1"
    },
    {
      "id": "182",
      "state": "FAILURE",
      "create_time": "2022-10-18 00:37:31.48",
      "end_time": "2022-10-18 00:37:31.65",
      "plugin_id": "63",
      "content": "show tables",
      "message": "Error -1 (00000) : while preparing SQL: show tables",
      "elapsed": "170",
      "user_id": "1"
    },
    {
      "id": "183",
      "state": "SUCCESS",
      "create_time": "2022-10-18 00:37:54.606",
      "end_time": "2022-10-18 00:37:57.7",
      "plugin_id": "68",
      "content": "show tables",
      "message": "null",
      "elapsed": "3094",
      "user_id": "1"
    },
    {
      "id": "184",
      "state": "FAILURE",
      "create_time": "2022-10-18 00:38:02.933",
      "end_time": "2022-10-18 00:38:21.492",
      "plugin_id": "68",
      "content": "use default",
      "message": "java.sql.BatchUpdateException: Code: 113. DB::Exception: There is no session or session context has expired. (THERE_IS_NO_SESSION) (version 22.7.6.74 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@1713839865",
      "elapsed": "18559",
      "user_id": "1"
    },
    {
      "id": "185",
      "state": "FAILURE",
      "create_time": "2022-10-18 00:38:51.703",
      "end_time": "2022-10-18 00:39:03.362",
      "plugin_id": "68",
      "content": "use default;\ninsert ",
      "message": "java.sql.BatchUpdateException: Code: 113. DB::Exception: There is no session or session context has expired. (THERE_IS_NO_SESSION) (version 22.7.6.74 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@1713839865",
      "elapsed": "11659",
      "user_id": "1"
    },
    {
      "id": "186",
      "state": "FAILURE",
      "create_time": "2022-10-18 00:39:39.275",
      "end_time": "2022-10-18 00:39:43.492",
      "plugin_id": "68",
      "content": "CREATE TABLE IF NOT EXISTS `audit_plugin`\n(\n    `id`          bigint(20) NOT NULL AUTO_INCREMENT,\n    `state`       varchar(255) COLLATE utf8_bin DEFAULT NULL,\n    `create_time` datetime(5)                   DEFAULT CURRENT_TIMESTAMP(5),\n    `end_time`    datetime(5)                   DEFAULT CURRENT_TIMESTAMP(5),\n    `plugin_id`   bigint(20) NOT NULL,\n    `content`     text COLLATE utf8_bin,\n    `message`     text COLLATE utf8_bin,\n    PRIMARY KEY (`id`)\n) DEFAULT CHARSET = utf8\n  COLLATE = utf8_bin;",
      "message": "java.sql.BatchUpdateException: Code: 62. DB::Exception: Syntax error: failed at position 463 ('DEFAULT') (line 11, col 3): DEFAULT CHARSET = utf8\n  COLLATE = utf8_bin. Expected one of: storage definition, ENGINE, PARTITION BY, PRIMARY KEY, ORDER BY, SAMPLE BY, TTL, EMPTY AS, AS, COMMENT, INTO OUTFILE, FORMAT, SETTINGS, end of query. (SYNTAX_ERROR) (version 22.7.6.74 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@1713839865",
      "elapsed": "4217",
      "user_id": "1"
    },
    {
      "id": "187",
      "state": "SUCCESS",
      "create_time": "2022-10-18 00:40:07.119",
      "end_time": "2022-10-18 00:40:09.599",
      "plugin_id": "68",
      "content": "show create test_table",
      "message": "null",
      "elapsed": "2480",
      "user_id": "1"
    },
    {
      "id": "188",
      "state": "FAILURE",
      "create_time": "2022-10-18 00:40:22.689",
      "end_time": "2022-10-18 00:40:28.143",
      "plugin_id": "68",
      "content": "CREATE TABLE default.test_table1 (`key` String, `value` UInt32, `ts` DateTime) ENGINE = MergeTree\nORDER BY\n  key SETTINGS index_granularity = 8192",
      "message": "java.sql.BatchUpdateException: Code: 164. DB::Exception: demo: Cannot execute query in readonly mode. (READONLY) (version 22.7.6.74 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@1713839865",
      "elapsed": "5454",
      "user_id": "1"
    },
    {
      "id": "221",
      "state": "FAILURE",
      "create_time": "2022-10-18 00:51:38.257",
      "end_time": "2022-10-18 00:51:41.803",
      "plugin_id": "68",
      "content": "CREATE TABLE test.test_table1 \n(name varchar(10),\n age int,\n ts datetime\n )\n\n",
      "message": "java.sql.BatchUpdateException: Code: 497. DB::Exception: demo: Not enough privileges. To execute this query it's necessary to have grant CREATE TABLE ON test.test_table1. (ACCESS_DENIED) (version 22.7.6.74 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@1851479581",
      "elapsed": "3546",
      "user_id": "1"
    },
    {
      "id": "222",
      "state": "FAILURE",
      "create_time": "2022-10-18 00:51:52.69",
      "end_time": "2022-10-18 00:51:53.365",
      "plugin_id": "63",
      "content": "CREATE TABLE test.test_table1 \n(name varchar(10),\n age int,\n ts datetime\n )\n\n",
      "message": "Error -1 (00000) : while preparing SQL: CREATE TABLE test.test_table1 \n(name varchar(10),\n age int,\n ts datetime\n )\n\n",
      "elapsed": "675",
      "user_id": "1"
    },
    {
      "id": "249",
      "state": "SUCCESS",
      "create_time": "2022-10-20 19:32:41.986",
      "end_time": "2022-10-20 19:32:45.856",
      "plugin_id": "68",
      "content": "show tables",
      "message": "null",
      "elapsed": "3870",
      "user_id": "5"
    },
    {
      "id": "269",
      "state": "FAILURE",
      "create_time": "2022-10-25 14:13:18.731",
      "end_time": "2022-10-25 14:13:20.566",
      "plugin_id": "63",
      "content": "show databases",
      "message": "Error -1 (00000) : while preparing SQL: show databases",
      "elapsed": "1835",
      "user_id": "2"
    },
    {
      "id": "307",
      "state": "SUCCESS",
      "create_time": "2022-10-27 13:02:31.998",
      "end_time": "2022-10-27 13:02:36.648",
      "plugin_id": "68",
      "content": "select concat('\\'', name, '\\',') from system.functions;",
      "message": "null",
      "elapsed": "4650",
      "user_id": "2"
    },
    {
      "id": "308",
      "state": "FAILURE",
      "create_time": "2022-10-27 13:13:47.234",
      "end_time": "2022-10-27 13:13:52.24",
      "plugin_id": "68",
      "content": "select * from aaa\nwhere aaa.id = 12;\n",
      "message": "java.sql.BatchUpdateException: Code: 60. DB::Exception: Table default.aaa doesn't exist. (UNKNOWN_TABLE) (version 22.9.3.18 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@272246408",
      "elapsed": "5006",
      "user_id": "2"
    },
    {
      "id": "309",
      "state": "SUCCESS",
      "create_time": "2022-10-27 13:14:05.295",
      "end_time": "2022-10-27 13:14:08.06",
      "plugin_id": "68",
      "content": "SHOW DATABASES",
      "message": "null",
      "elapsed": "2765",
      "user_id": "2"
    },
    {
      "id": "310",
      "state": "SUCCESS",
      "create_time": "2022-10-27 13:14:21.971",
      "end_time": "2022-10-27 13:14:24.48",
      "plugin_id": "68",
      "content": "show TABLES from default",
      "message": "null",
      "elapsed": "2509",
      "user_id": "2"
    },
    {
      "id": "311",
      "state": "SUCCESS",
      "create_time": "2022-10-27 13:15:03.509",
      "end_time": "2022-10-27 13:15:07.27",
      "plugin_id": "68",
      "content": "select * from (select * from default.github_events) LIMIT 100",
      "message": "null",
      "elapsed": "3761",
      "user_id": "2"
    },
    {
      "id": "319",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:25:47.587",
      "end_time": "2022-10-29 11:25:51.752",
      "plugin_id": "68",
      "content": "show tables",
      "message": "null",
      "elapsed": "4165",
      "user_id": "2"
    },
    {
      "id": "320",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:26:22.574",
      "end_time": "2022-10-29 11:26:24.374",
      "plugin_id": "63",
      "content": "select 1",
      "message": "null",
      "elapsed": "1800",
      "user_id": "2"
    },
    {
      "id": "321",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:26:50.083",
      "end_time": "2022-10-29 11:26:52.806",
      "plugin_id": "68",
      "content": "show tables",
      "message": "null",
      "elapsed": "2723",
      "user_id": "2"
    },
    {
      "id": "322",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:27:06.653",
      "end_time": "2022-10-29 11:27:09.184",
      "plugin_id": "68",
      "content": "show tables",
      "message": "null",
      "elapsed": "2531",
      "user_id": "2"
    },
    {
      "id": "323",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:27:30.975",
      "end_time": "2022-10-29 11:27:34.037",
      "plugin_id": "68",
      "content": "show tables",
      "message": "null",
      "elapsed": "3062",
      "user_id": "2"
    },
    {
      "id": "324",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:27:54.539",
      "end_time": "2022-10-29 11:27:57.201",
      "plugin_id": "68",
      "content": "SELECT * from github_events limit 100",
      "message": "null",
      "elapsed": "2662",
      "user_id": "2"
    },
    {
      "id": "325",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:28:19.661",
      "end_time": "2022-10-29 11:28:22.342",
      "plugin_id": "68",
      "content": "SELECT * from github_events limit 100",
      "message": "null",
      "elapsed": "2681",
      "user_id": "2"
    },
    {
      "id": "326",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:30:00.959",
      "end_time": "2022-10-29 11:30:03.667",
      "plugin_id": "68",
      "content": "show databases",
      "message": "null",
      "elapsed": "2708",
      "user_id": "2"
    },
    {
      "id": "328",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:45:53.315",
      "end_time": "2022-10-29 11:45:56.279",
      "plugin_id": "68",
      "content": "show databases",
      "message": "null",
      "elapsed": "2964",
      "user_id": "2"
    },
    {
      "id": "329",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:47:14.803",
      "end_time": "2022-10-29 11:47:17.777",
      "plugin_id": "68",
      "content": "show databases",
      "message": "null",
      "elapsed": "2974",
      "user_id": "2"
    },
    {
      "id": "330",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:47:54.437",
      "end_time": "2022-10-29 11:47:57.608",
      "plugin_id": "68",
      "content": "show databases",
      "message": "null",
      "elapsed": "3171",
      "user_id": "2"
    },
    {
      "id": "331",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:53:23.459",
      "end_time": "2022-10-29 11:53:26.112",
      "plugin_id": "68",
      "content": "SELECT \n      database as table_schema, \n      table as table_name, \n      name as column_name, \n      type as data_type \n    FROM \n      system.columns\n    WHERE database NOT IN ('system')\n    ORDER BY\n      table_schema,\n      table_name",
      "message": "null",
      "elapsed": "2653",
      "user_id": "2"
    },
    {
      "id": "332",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:54:10.959",
      "end_time": "2022-10-29 11:54:13.742",
      "plugin_id": "68",
      "content": "SELECT \n    database as table_schema, \n    table as table_name, \n    name as column_name, \n    type as data_type \nFROM \n    system.columns\nWHERE database NOT IN ('system')\nORDER BY\n    table_schema,\n    table_name",
      "message": "null",
      "elapsed": "2783",
      "user_id": "2"
    },
    {
      "id": "333",
      "state": "SUCCESS",
      "create_time": "2022-10-29 11:54:43.118",
      "end_time": "2022-10-29 11:54:45.787",
      "plugin_id": "68",
      "content": "SELECT\n  database as table_schema,\n  table as table_name,\n  name as column_name,\n  type as data_type\nFROM\n  system.columns\nWHERE\n  database NOT IN ('system')\nORDER BY\n  table_schema,\n  table_name",
      "message": "null",
      "elapsed": "2669",
      "user_id": "2"
    },
    {
      "id": "334",
      "state": "SUCCESS",
      "create_time": "2022-10-29 12:31:25.323",
      "end_time": "2022-10-29 12:31:28.094",
      "plugin_id": "68",
      "content": "show tables",
      "message": "null",
      "elapsed": "2771",
      "user_id": "2"
    },
    {
      "id": "337",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:07:07.647",
      "end_time": "2022-10-29 14:07:09.217",
      "plugin_id": "68",
      "content": "",
      "message": "query cannot be null, empty or blank string",
      "elapsed": "1570",
      "user_id": "2"
    },
    {
      "id": "338",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:07:17.87",
      "end_time": "2022-10-29 14:07:19.166",
      "plugin_id": "68",
      "content": "",
      "message": "query cannot be null, empty or blank string",
      "elapsed": "1296",
      "user_id": "2"
    },
    {
      "id": "339",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:13:40.219",
      "end_time": "2022-10-29 14:13:41.824",
      "plugin_id": "68",
      "content": "",
      "message": "query cannot be null, empty or blank string",
      "elapsed": "1605",
      "user_id": "2"
    },
    {
      "id": "340",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:13:41.995",
      "end_time": "2022-10-29 14:13:44.528",
      "plugin_id": "68",
      "content": "SELECT \n    database as table_schema, \n    table as table_name, \n    name as column_name, \n    type as data_type \nFROM system.columns\nWHERE database NOT IN ('system')\nORDER BY table_schema, table_name",
      "message": "null",
      "elapsed": "2533",
      "user_id": "2"
    },
    {
      "id": "341",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:14:53.425",
      "end_time": "2022-10-29 14:14:55.094",
      "plugin_id": "68",
      "content": "",
      "message": "query cannot be null, empty or blank string",
      "elapsed": "1669",
      "user_id": "2"
    },
    {
      "id": "342",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:15:06.637",
      "end_time": "2022-10-29 14:15:07.924",
      "plugin_id": "68",
      "content": "",
      "message": "query cannot be null, empty or blank string",
      "elapsed": "1287",
      "user_id": "2"
    },
    {
      "id": "343",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:15:21.306",
      "end_time": "2022-10-29 14:15:25.079",
      "plugin_id": "68",
      "content": "SELECT \n    database as table_schema, \n    table as table_name, \n    name as column_name, \n    type as data_type \nFROM system.columns\nWHERE database NOT IN ('system')\nORDER BY table_schema, table_name",
      "message": "null",
      "elapsed": "3773",
      "user_id": "2"
    },
    {
      "id": "344",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:16:37.478",
      "end_time": "2022-10-29 14:16:40.124",
      "plugin_id": "68",
      "content": "SELECT \n    database as table_schema, \n    table as table_name, \n    name as column_name, \n    type as data_type \nFROM system.columns\nWHERE database NOT IN ('system')\nORDER BY table_schema, table_name",
      "message": "null",
      "elapsed": "2646",
      "user_id": "2"
    },
    {
      "id": "345",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:22:08.507",
      "end_time": "2022-10-29 14:22:11.326",
      "plugin_id": "68",
      "content": "SELECT \n    database as table_schema, \n    table as table_name, \n    name as column_name, \n    type as data_type \nFROM system.columns\nWHERE database NOT IN ('system')\nORDER BY table_schema, table_name",
      "message": "null",
      "elapsed": "2819",
      "user_id": "2"
    },
    {
      "id": "347",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:22:51.95",
      "end_time": "2022-10-29 14:22:54.691",
      "plugin_id": "68",
      "content": "SELECT \n    database as table_schema, \n    table as table_name, \n    name as column_name, \n    type as data_type \nFROM system.columns\nWHERE database NOT IN ('system')\nORDER BY table_schema, table_name",
      "message": "null",
      "elapsed": "2741",
      "user_id": "2"
    },
    {
      "id": "348",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:31:14.07",
      "end_time": "2022-10-29 14:31:17.055",
      "plugin_id": "68",
      "content": "SELECT \n    database as tableSchema, \n    table as tableName, \n    name as columnName, \n    type as dataType \nFROM system.columns\nWHERE database NOT IN ('system')\nORDER BY table_schema, table_name",
      "message": "java.sql.BatchUpdateException: Code: 47. DB::Exception: Missing columns: 'table_name' 'table_schema' while processing query: 'SELECT database AS tableSchema, table AS tableName, name AS columnName, type AS dataType FROM system.columns WHERE database NOT IN ('system') ORDER BY table_schema ASC, table_name ASC', required columns: 'database' 'table' 'type' 'name' 'table_schema' 'table_name', maybe you meant: ['database','table','type','name']. (UNKNOWN_IDENTIFIER) (version 22.9.3.18 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@553671121",
      "elapsed": "2985",
      "user_id": "2"
    },
    {
      "id": "349",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:31:41.404",
      "end_time": "2022-10-29 14:31:43.971",
      "plugin_id": "68",
      "content": "SELECT database as tableSchema, table as tableName, name as columnName, type as dataType \nFROM system.columns\nWHERE database NOT IN ('system')\nORDER BY table_schema, table_name",
      "message": "java.sql.BatchUpdateException: Code: 47. DB::Exception: Missing columns: 'table_name' 'table_schema' while processing query: 'SELECT database AS tableSchema, table AS tableName, name AS columnName, type AS dataType FROM system.columns WHERE database NOT IN ('system') ORDER BY table_schema ASC, table_name ASC', required columns: 'database' 'table' 'type' 'name' 'table_schema' 'table_name', maybe you meant: ['database','table','type','name']. (UNKNOWN_IDENTIFIER) (version 22.9.3.18 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@553671121",
      "elapsed": "2567",
      "user_id": "2"
    },
    {
      "id": "350",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:32:31.655",
      "end_time": "2022-10-29 14:32:35.784",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns +\n          WHERE database NOT IN ('system') +\n          ORDER BY table_schema, table_name\n        ",
      "message": "java.sql.BatchUpdateException: Code: 62. DB::Exception: Syntax error: failed at position 131 ('+') (line 3, col 31): +\n          WHERE database NOT IN ('system') +\n          ORDER BY table_schema, table_name\n        . Expected one of: token, Dot, UUID, alias, AS, identifier, FINAL, SAMPLE, table, table function, subquery or list of joined tables, array join, LEFT ARRAY JOIN, INNER, ARRAY JOIN, JOIN, PREWHERE, WHERE, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 22.9.3.18 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@553671121",
      "elapsed": "4129",
      "user_id": "2"
    },
    {
      "id": "351",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:33:01.008",
      "end_time": "2022-10-29 14:33:03.591",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns +\n          WHERE database NOT IN ('system') +\n          ORDER BY table_schema, table_name\n        ",
      "message": "java.sql.BatchUpdateException: Code: 62. DB::Exception: Syntax error: failed at position 131 ('+') (line 3, col 31): +\n          WHERE database NOT IN ('system') +\n          ORDER BY table_schema, table_name\n        . Expected one of: token, Dot, UUID, alias, AS, identifier, FINAL, SAMPLE, table, table function, subquery or list of joined tables, array join, LEFT ARRAY JOIN, INNER, ARRAY JOIN, JOIN, PREWHERE, WHERE, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 22.9.3.18 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@553671121",
      "elapsed": "2583",
      "user_id": "2"
    },
    {
      "id": "352",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:36:08.086",
      "end_time": "2022-10-29 14:36:10.856",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns +\n          WHERE database NOT IN ('system') +\n          ORDER BY table_schema, table_name\n        ",
      "message": "java.sql.BatchUpdateException: Code: 62. DB::Exception: Syntax error: failed at position 131 ('+') (line 3, col 31): +\n          WHERE database NOT IN ('system') +\n          ORDER BY table_schema, table_name\n        . Expected one of: token, Dot, UUID, alias, AS, identifier, FINAL, SAMPLE, table, table function, subquery or list of joined tables, array join, LEFT ARRAY JOIN, INNER, ARRAY JOIN, JOIN, PREWHERE, WHERE, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 22.9.3.18 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@553671121",
      "elapsed": "2770",
      "user_id": "2"
    },
    {
      "id": "353",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:36:24.164",
      "end_time": "2022-10-29 14:36:26.85",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns +\n          WHERE database NOT IN ('system')\n          ORDER BY table_schema, table_name\n        ",
      "message": "java.sql.BatchUpdateException: Code: 62. DB::Exception: Syntax error: failed at position 131 ('+') (line 3, col 31): +\n          WHERE database NOT IN ('system')\n          ORDER BY table_schema, table_name\n        . Expected one of: token, Dot, UUID, alias, AS, identifier, FINAL, SAMPLE, table, table function, subquery or list of joined tables, array join, LEFT ARRAY JOIN, INNER, ARRAY JOIN, JOIN, PREWHERE, WHERE, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 22.9.3.18 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@553671121",
      "elapsed": "2686",
      "user_id": "2"
    },
    {
      "id": "354",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:36:39.715",
      "end_time": "2022-10-29 14:36:42.625",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns +\n          WHERE database NOT IN ('system')\n          ORDER BY table_schema, table_name\n        ",
      "message": "java.sql.BatchUpdateException: Code: 62. DB::Exception: Syntax error: failed at position 131 ('+') (line 3, col 31): +\n          WHERE database NOT IN ('system')\n          ORDER BY table_schema, table_name\n        . Expected one of: token, Dot, UUID, alias, AS, identifier, FINAL, SAMPLE, table, table function, subquery or list of joined tables, array join, LEFT ARRAY JOIN, INNER, ARRAY JOIN, JOIN, PREWHERE, WHERE, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 22.9.3.18 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@553671121",
      "elapsed": "2910",
      "user_id": "2"
    },
    {
      "id": "355",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:36:57.224",
      "end_time": "2022-10-29 14:36:59.927",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY table_schema, table_name\n        ",
      "message": "java.sql.BatchUpdateException: Code: 47. DB::Exception: Missing columns: 'table_name' 'table_schema' while processing query: 'SELECT database AS tableSchema, table AS tableName, name AS columnName, type AS dataType FROM system.columns WHERE database NOT IN ('system') ORDER BY table_schema ASC, table_name ASC', required columns: 'database' 'table' 'type' 'name' 'table_schema' 'table_name', maybe you meant: ['database','table','type','name']. (UNKNOWN_IDENTIFIER) (version 22.9.3.18 (official build))\n, server ClickHouseNode(addr=http:github.demo.altinity.cloud:8443, db=default)@553671121",
      "elapsed": "2703",
      "user_id": "2"
    },
    {
      "id": "356",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:37:17.77",
      "end_time": "2022-10-29 14:37:20.72",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2950",
      "user_id": "2"
    },
    {
      "id": "357",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:42:41.421",
      "end_time": "2022-10-29 14:42:44.291",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2870",
      "user_id": "2"
    },
    {
      "id": "358",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:44:42.122",
      "end_time": "2022-10-29 14:44:44.879",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2757",
      "user_id": "2"
    },
    {
      "id": "359",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:47:03.028",
      "end_time": "2022-10-29 14:47:05.943",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2915",
      "user_id": "2"
    },
    {
      "id": "360",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:47:25.123",
      "end_time": "2022-10-29 14:47:28.032",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2909",
      "user_id": "2"
    },
    {
      "id": "361",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:47:42.339",
      "end_time": "2022-10-29 14:47:44.941",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2602",
      "user_id": "2"
    },
    {
      "id": "362",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:48:28.421",
      "end_time": "2022-10-29 14:48:31.212",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2791",
      "user_id": "2"
    },
    {
      "id": "363",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:49:16.65",
      "end_time": "2022-10-29 14:49:19.409",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2759",
      "user_id": "2"
    },
    {
      "id": "364",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:49:57.989",
      "end_time": "2022-10-29 14:50:00.82",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2831",
      "user_id": "2"
    },
    {
      "id": "365",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:50:06.813",
      "end_time": "2022-10-29 14:50:09.709",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2896",
      "user_id": "2"
    },
    {
      "id": "366",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:52:18.326",
      "end_time": "2022-10-29 14:52:21.38",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "3054",
      "user_id": "2"
    },
    {
      "id": "367",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:52:33.243",
      "end_time": "2022-10-29 14:52:35.732",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2489",
      "user_id": "2"
    },
    {
      "id": "368",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:53:01.765",
      "end_time": "2022-10-29 14:53:04.24",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2475",
      "user_id": "2"
    },
    {
      "id": "369",
      "state": "FAILURE",
      "create_time": "2022-10-29 14:54:53.729",
      "end_time": "2022-10-29 14:54:54.049",
      "plugin_id": "63",
      "content": "",
      "message": "Error -1 (00000) : while preparing SQL: ",
      "elapsed": "320",
      "user_id": "2"
    },
    {
      "id": "370",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:55:07.663",
      "end_time": "2022-10-29 14:55:10.428",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2765",
      "user_id": "2"
    },
    {
      "id": "371",
      "state": "SUCCESS",
      "create_time": "2022-10-29 14:57:20.301",
      "end_time": "2022-10-29 14:57:23.249",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2948",
      "user_id": "2"
    },
    {
      "id": "374",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:00:16.703",
      "end_time": "2022-10-29 15:00:19.445",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2742",
      "user_id": "2"
    },
    {
      "id": "377",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:02:53.705",
      "end_time": "2022-10-29 15:02:57.681",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "3976",
      "user_id": "2"
    },
    {
      "id": "378",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:04:14.374",
      "end_time": "2022-10-29 15:04:17.125",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2751",
      "user_id": "2"
    },
    {
      "id": "379",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:04:26.765",
      "end_time": "2022-10-29 15:04:29.329",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2564",
      "user_id": "2"
    },
    {
      "id": "380",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:06:25.33",
      "end_time": "2022-10-29 15:06:30.158",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "4828",
      "user_id": "2"
    },
    {
      "id": "381",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:07:06.298",
      "end_time": "2022-10-29 15:07:09.289",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2991",
      "user_id": "2"
    },
    {
      "id": "382",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:07:15.523",
      "end_time": "2022-10-29 15:07:17.936",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2413",
      "user_id": "2"
    },
    {
      "id": "383",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:07:27.604",
      "end_time": "2022-10-29 15:07:30.128",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2524",
      "user_id": "2"
    },
    {
      "id": "384",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:09:28.083",
      "end_time": "2022-10-29 15:09:30.977",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2894",
      "user_id": "2"
    },
    {
      "id": "385",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:09:42.388",
      "end_time": "2022-10-29 15:09:45.111",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2723",
      "user_id": "2"
    },
    {
      "id": "386",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:10:22.449",
      "end_time": "2022-10-29 15:10:25.05",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2601",
      "user_id": "2"
    },
    {
      "id": "387",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:11:49.644",
      "end_time": "2022-10-29 15:11:52.508",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2864",
      "user_id": "2"
    },
    {
      "id": "388",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:12:09.343",
      "end_time": "2022-10-29 15:12:12.074",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2731",
      "user_id": "2"
    },
    {
      "id": "389",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:13:23.928",
      "end_time": "2022-10-29 15:13:26.548",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2620",
      "user_id": "2"
    },
    {
      "id": "390",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:13:32.314",
      "end_time": "2022-10-29 15:13:35.098",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2784",
      "user_id": "2"
    },
    {
      "id": "391",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:18:22.183",
      "end_time": "2022-10-29 15:18:24.792",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2609",
      "user_id": "2"
    },
    {
      "id": "392",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:18:37.288",
      "end_time": "2022-10-29 15:18:39.881",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2593",
      "user_id": "2"
    },
    {
      "id": "399",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:24:07.522",
      "end_time": "2022-10-29 15:24:10.313",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2791",
      "user_id": "2"
    },
    {
      "id": "400",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:24:24.775",
      "end_time": "2022-10-29 15:24:27.639",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2864",
      "user_id": "2"
    },
    {
      "id": "401",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:24:43.552",
      "end_time": "2022-10-29 15:24:48.174",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "4622",
      "user_id": "2"
    },
    {
      "id": "402",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:27:02.772",
      "end_time": "2022-10-29 15:27:05.635",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2863",
      "user_id": "2"
    },
    {
      "id": "403",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:27:16.181",
      "end_time": "2022-10-29 15:27:18.836",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2655",
      "user_id": "2"
    },
    {
      "id": "409",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:44:22.241",
      "end_time": "2022-10-29 15:44:25.039",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2798",
      "user_id": "2"
    },
    {
      "id": "413",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:49:55.865",
      "end_time": "2022-10-29 15:49:58.461",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2596",
      "user_id": "2"
    },
    {
      "id": "414",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:50:27.957",
      "end_time": "2022-10-29 15:50:30.476",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2519",
      "user_id": "2"
    },
    {
      "id": "415",
      "state": "SUCCESS",
      "create_time": "2022-10-29 15:50:47.327",
      "end_time": "2022-10-29 15:50:49.971",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2644",
      "user_id": "2"
    },
    {
      "id": "417",
      "state": "SUCCESS",
      "create_time": "2022-10-29 16:04:38.609",
      "end_time": "2022-10-29 16:04:41.255",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "2646",
      "user_id": "2"
    },
    {
      "id": "429",
      "state": "SUCCESS",
      "create_time": "2022-10-29 16:45:35.159",
      "end_time": "2022-10-29 16:45:38.232",
      "plugin_id": "68",
      "content": "\n          SELECT database as tableSchema, table as tableName, name as columnName, type as dataType\n          FROM system.columns\n          WHERE database NOT IN ('system')\n          ORDER BY tableSchema, tableName\n        ",
      "message": "null",
      "elapsed": "3073",
      "user_id": "2"
    }
  ]
}
export default {
  data
}
