import '@/ace-editor-theme'

const themes = [
    'ambiance',
    'chaos',
    'chrome',
    'clouds',
    'cloud9_day',
    'cloud9_night',
    'cloud9_night_low_color',
    'clouds_midnight',
    'cobalt',
    'crimson_editor',
    'dawn',
    'dracula',
    'dreamweaver',
    'eclipse',
    'github',
    'gob',
    'github_dark',
    'gruvbox',
    'gruvbox_dark_hard',
    'gruvbox_light_hard',
    'iplastic',
    'idle_fingers',
    'kr_theme',
    'katzenmilch',
    'kuroir',
    'monokai',
    'merbivore',
    'mono_industrial',
    'nord_dark',
    'one_dark',
    'pastel_on_dark',
    'sqlserver',
    'solarized_dark',
    'solarized_light',
    'terminal',
    'textmate',
    'tomorrow_night',
    'tomorrow_night_blue',
    'tomorrow_night_bright',
    'tomorrow_night_eighties',
    'tomorrow',
    'twilight',
    'vibrant_ink',
    'xcode'
];

export default {
    themes
}
